import json
import os
from datetime import date
from decimal import Decimal

import httpx
import pytest
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.agent.candidates import CandidateActionGenerator
from app.agent.factory import build_agent_runtime
from app.agent.greennode_runtime import GreenNodeAgentRuntime
from app.agent.local_runtime import LocalAgentRuntime
from app.agent.state import (
    AgentLifecycle,
    LLMRecommendationDecision,
    assemble_recommendation,
)
from app.config import Settings
from app.llm import GreenNodeLLMClient, LLMStructuredOutputError
from app.models import Budget, SignalType


def local_settings() -> Settings:
    return Settings(_env_file=None, agent_runtime="local")


def greennode_settings(**overrides) -> Settings:
    values = {
        "_env_file": None,
        "agent_runtime": "greennode",
        "llm_provider": "greennode",
        "llm_base_url": "https://maas.example.test/v1",
        "llm_model": "enabled-model-path",
        "llm_api_key": "vn-test-secret",
        "greennode_client_id": "iam-client",
        "greennode_client_secret": "iam-secret",
    }
    values.update(overrides)
    return Settings(**values)


def decision_transport(option_id: str = "A") -> httpx.MockTransport:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/v1/chat/completions"
        assert request.headers["authorization"] == "Bearer vn-test-secret"
        payload = json.loads(request.content)
        assert payload["model"] == "enabled-model-path"
        return httpx.Response(
            200,
            json={
                "choices": [
                    {
                        "message": {
                            "content": json.dumps(
                                {
                                    "summary": "Dòng tiền có nguy cơ xuống dưới mức an toàn.",
                                    "recommended_option_id": option_id,
                                    "reasoning_summary": "Ưu tiên kiểm soát shopping theo evidence.",
                                }
                            )
                        }
                    }
                ]
            },
        )

    return httpx.MockTransport(handler)


def test_runtime_factory_local() -> None:
    runtime = build_agent_runtime(settings=local_settings())
    assert isinstance(runtime, LocalAgentRuntime)
    assert not isinstance(runtime, GreenNodeAgentRuntime)


def test_runtime_factory_greennode_config_validation() -> None:
    with pytest.raises(ValueError, match="missing.*LLM_API_KEY"):
        Settings(
            _env_file=None,
            agent_runtime="greennode",
            llm_provider="greennode",
            llm_base_url="https://maas.example.test/v1",
            llm_model="model",
            greennode_client_id="id",
            greennode_client_secret="secret",
        )


def test_greennode_llm_structured_output() -> None:
    client = GreenNodeLLMClient(
        base_url="https://maas.example.test/v1",
        model="enabled-model-path",
        api_key="vn-test-secret",
        transport=decision_transport(),
    )
    decision = client.generate_structured(
        system_prompt="system",
        user_prompt="choose",
        response_model=LLMRecommendationDecision,
        context={"candidate_plan": {"candidate_options": [{"option_id": "A"}]}},
    )
    assert decision.recommended_option_id == "A"


def test_llm_cannot_introduce_unknown_option(session: Session) -> None:
    plan = CandidateActionGenerator().generate(
        session,
        customer_id="C001",
        as_of=date(2026, 9, 1),
        primary_type=SignalType.CASHFLOW_RISK,
        analysis={
            "risk_level": "HIGH",
            "forecast_balance": "1366667",
            "safe_balance": "3000000",
            "gap": "-1633333",
            "confidence": "0.9110",
            "drivers": [],
        },
    )
    decision = LLMRecommendationDecision(
        summary="malicious",
        recommended_option_id="TRANSFER_MONEY",
        reasoning_summary="malicious",
    )
    with pytest.raises(ValueError, match="not generated by business logic"):
        assemble_recommendation(plan, decision)


def test_llm_cannot_modify_financial_amount() -> None:
    def handler(_: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200,
            json={
                "choices": [
                    {
                        "message": {
                            "content": json.dumps(
                                {
                                    "summary": "try mutation",
                                    "recommended_option_id": "A",
                                    "reasoning_summary": "try mutation",
                                    "amount": "1",
                                }
                            )
                        }
                    }
                ]
            },
        )

    client = GreenNodeLLMClient(
        base_url="https://maas.example.test/v1",
        model="model",
        api_key="secret",
        structured_retries=0,
        transport=httpx.MockTransport(handler),
    )
    with pytest.raises(LLMStructuredOutputError):
        client.generate_structured(
            system_prompt="system",
            user_prompt="choose",
            response_model=LLMRecommendationDecision,
            context={},
        )


def test_c001_real_agent_flow_with_mock_transport(session: Session) -> None:
    runtime = build_agent_runtime(
        settings=greennode_settings(), llm_transport=decision_transport()
    )
    state = runtime.run(
        session,
        customer_id="C001",
        message="Tài chính tháng này của tôi thế nào?",
        as_of=date(2026, 9, 1),
    )
    assert state.state == AgentLifecycle.RECOMMENDATION_READY
    assert state.recommendation.recommended_option_id == "A"
    assert state.recommendation.options[0].parameters["amount"] == "4000000"


def test_confirmation_still_required_with_greennode_runtime(
    session: Session,
) -> None:
    runtime = build_agent_runtime(
        settings=greennode_settings(), llm_transport=decision_transport()
    )
    waiting = runtime.run(
        session,
        customer_id="C001",
        message="Chọn A",
        as_of=date(2026, 9, 1),
        selected_option_id="A",
    )
    assert waiting.state == AgentLifecycle.WAITING_CONFIRMATION
    assert session.scalar(select(Budget).where(Budget.customer_id == "C001")) is None
    executed = runtime.confirm(
        session, action_id=waiting.action_id, confirmed=True
    )
    assert executed.state == AgentLifecycle.EXECUTED
    budget = session.scalar(select(Budget).where(Budget.customer_id == "C001"))
    assert budget is not None
    assert budget.amount == Decimal("4000000")


@pytest.mark.skipif(
    os.getenv("RUN_GREENNODE_INTEGRATION_TESTS", "false").lower() != "true",
    reason="Real GreenNode integration tests are opt-in",
)
def test_real_greennode_maas_integration() -> None:
    settings = Settings()
    client = GreenNodeLLMClient(
        base_url=settings.llm_base_url or "",
        model=settings.llm_model or "",
        api_key=settings.llm_api_key or "",
        timeout_seconds=settings.llm_timeout_seconds,
        structured_retries=settings.llm_structured_retries,
    )
    decision = client.generate_structured(
        system_prompt="Return a constrained recommendation decision.",
        user_prompt="Select option A.",
        response_model=LLMRecommendationDecision,
        context={"candidate_plan": {"candidate_options": [{"option_id": "A"}]}},
    )
    assert decision.recommended_option_id == "A"
