services:
  frontend-mobile:
    build:
      context: ../..
      dockerfile: deploy/production/mobile.Dockerfile
    env_file: ./mobile.env
    ports:
      - "${MOBILE_BIND_IP:-0.0.0.0}:80:80"
    restart: unless-stopped
